# Generated by Django 5.1 on 2024-09-08 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_expense_incomes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Incomes',
        ),
    ]
